"""CORE Runtime - Single Source of Truth for Version.

This file is the canonical version source. All other version references
(pyproject.toml, core_runtime/__init__.py, documentation) should be
kept in sync with this value.

DO NOT EDIT THIS FILE MANUALLY.
Use scripts/bump_version.py to update versions consistently.
"""

__version__ = "11.6.0"

# Component versions
CORE_VERSION = "11.6.0"

# Parsed version tuple for programmatic comparison
VERSION_INFO = tuple(int(x) for x in __version__.split("."))
