#!/usr/bin/env python3
"""Create a deterministic offline CORE adapter skeleton."""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core_runtime.core.sensor_evidence import (  # noqa: E402
    SensorSource,
    derive_threshold_observation_event,
    load_sensor_trace_csv,
)


ADAPTER_NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
VALUE_KEY_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
DEFAULT_OUTPUT_DIR = Path("examples/adapters")
DEFAULT_SAMPLE_COUNT = 100


def _validate_name(value: str, field_name: str) -> str:
    if not isinstance(value, str) or not ADAPTER_NAME_PATTERN.fullmatch(value):
        raise ValueError(
            f"{field_name} must match ^[a-z][a-z0-9_]*$ "
            "(lowercase letters, numbers, underscores; must start with a letter)"
        )
    return value


def _validate_value_key(value: str) -> str:
    if not isinstance(value, str) or not VALUE_KEY_PATTERN.fullmatch(value):
        raise ValueError(
            "value_key must match ^[a-z][a-z0-9_]*$ "
            "(lowercase letters, numbers, underscores; must start with a letter)"
        )
    return value


def _normalize_optional_text(value: str | None, field_name: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError(f"{field_name} must be a string if provided")
    normalized = value.strip()
    if not normalized:
        raise ValueError(f"{field_name} must not be empty if provided")
    return normalized


def _canonical_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def _write_samples(path: Path, *, value_key: str, threshold: float) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["index", "logical_time", value_key],
        )
        writer.writeheader()

        for index in range(DEFAULT_SAMPLE_COUNT):
            if 30 <= index <= 45:
                value = threshold + 1.5
            else:
                value = max(0.0, threshold - 5.0) + ((index % 5) * 0.1)

            writer.writerow(
                {
                    "index": index,
                    "logical_time": f"t{index:03d}",
                    value_key: f"{value:.2f}",
                }
            )


def _adapter_readme(*, adapter_name: str, fixture_id: str) -> str:
    return f"""# {adapter_name}

This adapter skeleton was generated by `scripts/create_adapter_skeleton.py`.

It is an offline, simulated adapter example. It does not use live hardware,
network access, GPU, Kaggle, or runtime mutation.

## Generate fixture

```bash
python generate_fixture.py
```

## Validate

```bash
python scripts/validate_sensor_manifest.py examples/adapters/{adapter_name}/fixtures/{fixture_id}
```

## Certify

```bash
python scripts/certify_sensor_fixture.py examples/adapters/{adapter_name}/fixtures/{fixture_id}
```

## Scope

This adapter:

- produces a deterministic `SensorTrace`
- produces a deterministic `ObservationEvent`
- includes a `manifest.json` with fingerprints
- passes CORE validator and certifier
- does not modify `core_runtime/`
- does not mutate runtime, scheduler, replay, or KnowledgeBase internals

## Next steps for forks

Use this skeleton as a starting point for a downstream adapter.

Do not add live hardware integration until the offline fixture validates and
certifies.
"""


def _generated_fixture_script(
    *,
    adapter_name: str,
    value_key: str,
    threshold: float,
    sensor_id: str,
    trace_id: str,
    event_id: str,
    event_type: str,
) -> str:
    script_template = """#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path


def _find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "core_runtime").exists():
            return candidate
    raise RuntimeError("Unable to locate CORE project root")


PROJECT_ROOT = _find_project_root(Path.cwd())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core_runtime.core.sensor_evidence import (  # noqa: E402
    SensorSource,
    derive_threshold_observation_event,
    load_sensor_trace_csv,
)


ROOT = Path(__file__).resolve().parent
FIXTURE_ID = __FIXTURE_ID__
FIXTURE_DIR = ROOT / "fixtures" / FIXTURE_ID
SAMPLES_CSV = FIXTURE_DIR / "samples.csv"
MANIFEST_JSON = FIXTURE_DIR / "manifest.json"

ADAPTER_NAME = __ADAPTER_NAME__
VALUE_KEY = __VALUE_KEY__
THRESHOLD = __THRESHOLD__
SENSOR_ID = __SENSOR_ID__
TRACE_ID = __TRACE_ID__
EVENT_ID = __EVENT_ID__
EVENT_TYPE = __EVENT_TYPE__


def _write_samples() -> None:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    with SAMPLES_CSV.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["index", "logical_time", VALUE_KEY],
        )
        writer.writeheader()

        for index in range(100):
            if 30 <= index <= 45:
                value = THRESHOLD + 1.5
            else:
                value = max(0.0, THRESHOLD - 5.0) + ((index % 5) * 0.1)

            writer.writerow(
                {
                    "index": index,
                    "logical_time": f"t{index:03d}",
                    VALUE_KEY: f"{value:.2f}",
                }
            )


def _build_manifest() -> dict[str, object]:
    source = SensorSource(
        sensor_id=SENSOR_ID,
        sensor_type=ADAPTER_NAME,
        capture_mode="offline_fixture",
        calibration_id=f"calibration:{ADAPTER_NAME}:v1",
        environment_id="environment:example",
    )

    trace = load_sensor_trace_csv(
        SAMPLES_CSV,
        trace_id=TRACE_ID,
        source=source,
    )

    event = derive_threshold_observation_event(
        trace,
        event_id=EVENT_ID,
        event_type=EVENT_TYPE,
        value_key=VALUE_KEY,
        threshold=THRESHOLD,
    )

    return {
        "fixture_id": f"{ADAPTER_NAME}_v1",
        "schema_version": "core.sensor_evidence.v1",
        "trace_id": TRACE_ID,
        "sensor_id": SENSOR_ID,
        "expected_trace_id": TRACE_ID,
        "expected_sensor_id": SENSOR_ID,
        "sensor_type": ADAPTER_NAME,
        "capture_mode": "offline_fixture",
        "calibration_id": f"calibration:{ADAPTER_NAME}:v1",
        "environment_id": "environment:example",
        "sample_count": 100,
        "value_keys": [VALUE_KEY],
        "value_key": VALUE_KEY,
        "threshold": THRESHOLD,
        "expected_event_type": EVENT_TYPE,
        "observation_event_id": EVENT_ID,
        "trace_fingerprint": trace.fingerprint(),
        "observation_event_fingerprints": {
            event.event_id: event.fingerprint(),
        },
        "notes": [
            "Generated CORE adapter skeleton.",
            "Offline-only.",
            "No hardware dependency.",
            "No runtime authority is granted to adapter data.",
        ],
    }


def main() -> int:
    _write_samples()
    manifest = _build_manifest()

    MANIFEST_JSON.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\\n",
        encoding="utf-8",
    )

    print(f"Wrote fixture: {FIXTURE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""
    return (
        script_template.replace("__FIXTURE_ID__", json.dumps(f"{adapter_name}_v1"))
        .replace("__ADAPTER_NAME__", json.dumps(adapter_name))
        .replace("__VALUE_KEY__", json.dumps(value_key))
        .replace("__THRESHOLD__", repr(threshold))
        .replace("__SENSOR_ID__", json.dumps(sensor_id))
        .replace("__TRACE_ID__", json.dumps(trace_id))
        .replace("__EVENT_ID__", json.dumps(event_id))
        .replace("__EVENT_TYPE__", json.dumps(event_type))
    )


def create_adapter_skeleton(
    *,
    adapter_name: str,
    output_dir: Path,
    value_key: str,
    threshold: float,
    sensor_id: str | None,
    trace_id: str | None,
    force: bool,
) -> Path:
    adapter_name = _validate_name(adapter_name, "adapter_name")
    value_key = _validate_value_key(value_key)

    resolved_sensor_id = _normalize_optional_text(sensor_id, "sensor_id") or f"sensor:{adapter_name}:v1"
    resolved_trace_id = _normalize_optional_text(trace_id, "trace_id") or f"trace:{adapter_name}:v1"
    event_id = f"event:{adapter_name}:threshold:v1"
    event_type = f"sensor.{adapter_name}.threshold_crossing"

    adapter_dir = output_dir / adapter_name
    fixture_dir = adapter_dir / "fixtures" / f"{adapter_name}_v1"

    if adapter_dir.exists():
        if not force:
            raise FileExistsError(
                f"Adapter directory already exists: {adapter_dir}. Use --force to overwrite."
            )
        shutil.rmtree(adapter_dir)

    fixture_dir.mkdir(parents=True, exist_ok=True)

    readme_path = adapter_dir / "README.md"
    script_path = adapter_dir / "generate_fixture.py"
    samples_path = fixture_dir / "samples.csv"
    manifest_path = fixture_dir / "manifest.json"

    _write_text(
        script_path,
        _generated_fixture_script(
            adapter_name=adapter_name,
            value_key=value_key,
            threshold=threshold,
            sensor_id=resolved_sensor_id,
            trace_id=resolved_trace_id,
            event_id=event_id,
            event_type=event_type,
        ),
    )

    _write_samples(samples_path, value_key=value_key, threshold=threshold)

    source = SensorSource(
        sensor_id=resolved_sensor_id,
        sensor_type=adapter_name,
        capture_mode="offline_fixture",
        calibration_id=f"calibration:{adapter_name}:v1",
        environment_id="environment:example",
    )

    trace = load_sensor_trace_csv(
        samples_path,
        trace_id=resolved_trace_id,
        source=source,
    )

    event = derive_threshold_observation_event(
        trace,
        event_id=event_id,
        event_type=event_type,
        value_key=value_key,
        threshold=threshold,
    )

    manifest = {
        "fixture_id": f"{adapter_name}_v1",
        "schema_version": "core.sensor_evidence.v1",
        "trace_id": resolved_trace_id,
        "sensor_id": resolved_sensor_id,
        "expected_trace_id": resolved_trace_id,
        "expected_sensor_id": resolved_sensor_id,
        "sensor_type": adapter_name,
        "capture_mode": "offline_fixture",
        "calibration_id": f"calibration:{adapter_name}:v1",
        "environment_id": "environment:example",
        "sample_count": DEFAULT_SAMPLE_COUNT,
        "value_keys": [value_key],
        "value_key": value_key,
        "threshold": threshold,
        "expected_event_type": event_type,
        "observation_event_id": event_id,
        "trace_fingerprint": trace.fingerprint(),
        "observation_event_fingerprints": {
            event.event_id: event.fingerprint(),
        },
        "notes": [
            "Generated CORE adapter skeleton.",
            "Offline-only.",
            "No hardware dependency.",
            "No runtime authority is granted to adapter data.",
        ],
    }

    _write_text(manifest_path, _canonical_json(manifest))
    _write_text(
        readme_path,
        _adapter_readme(
            adapter_name=adapter_name,
            fixture_id=f"{adapter_name}_v1",
        ),
    )

    return adapter_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a deterministic offline CORE adapter skeleton.",
    )
    parser.add_argument("adapter_name", help="Adapter name using lowercase letters, numbers, and underscores.")
    parser.add_argument("--value-key", default="signal", help="Value column to emit in the generated fixture.")
    parser.add_argument("--threshold", type=float, default=1.0, help="Threshold used to derive the observation event.")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR), help="Directory where the adapter skeleton is created.")
    parser.add_argument("--sensor-id", default=None, help="Optional sensor id override.")
    parser.add_argument("--trace-id", default=None, help="Optional trace id override.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing adapter directory.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        adapter_dir = create_adapter_skeleton(
            adapter_name=args.adapter_name,
            output_dir=Path(args.output_dir),
            value_key=args.value_key,
            threshold=args.threshold,
            sensor_id=args.sensor_id,
            trace_id=args.trace_id,
            force=args.force,
        )
    except (ValueError, FileExistsError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"Wrote adapter skeleton: {adapter_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
