#!/usr/bin/env python3
"""Generate the reproducibility lockfile for CORE certification.

The lock is intentionally curated for the certification path:
- it includes the runtime and test dependencies used by the repo
- it excludes platform-specific CUDA/NVIDIA wheels
- optional extras such as pytest-xdist are intentionally omitted

Usage:
    python scripts/generate_requirements_lock.py > requirements.lock
"""

from __future__ import annotations

from importlib import metadata
from pathlib import Path
import sys

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


SEEDS = [
    "jsonschema",
    "pytest",
    "packaging",
    "setuptools",
    "wheel",
]

EXCLUDE_PREFIXES = ("cuda-", "nvidia-")
EXCLUDE_NAMES: set[str] = set()


def _is_excluded(name: str) -> bool:
    return name in EXCLUDE_NAMES or any(name.startswith(prefix) for prefix in EXCLUDE_PREFIXES)


def build_lock_entries() -> list[tuple[str, str]]:
    seen: set[str] = set()
    resolved: dict[str, str] = {}
    queue = list(SEEDS)

    while queue:
        name = queue.pop(0)
        norm = canonicalize_name(name)
        if norm in seen or _is_excluded(norm):
            continue
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            continue

        seen.add(norm)
        resolved[norm] = dist.version

        for requirement in dist.requires or []:
            req = Requirement(requirement)
            if req.marker is not None and not req.marker.evaluate():
                continue
            dep_name = canonicalize_name(req.name)
            if _is_excluded(dep_name):
                continue
            queue.append(req.name)

    return sorted(resolved.items())


def render_lock() -> str:
    lines = [
        "# CORE reproducibility lockfile",
        "# Generated by scripts/generate_requirements_lock.py",
        "# Optional extras such as pytest-xdist are intentionally excluded.",
        "",
    ]
    lines.extend(f"{name}=={version}" for name, version in build_lock_entries())
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    output = render_lock()
    if argv is None:
        argv = sys.argv[1:]
    if argv:
        Path(argv[0]).write_text(output, encoding="utf-8")
        return 0
    sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
